project:
  type: website
  output-dir: docs

website:
  title: "resources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CNM6011_ListaExercicios_Unidade2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

